#este e um plugin destinado ao Curriculo Na Enxada, qualquer um que tenha acesso, apenas fins de estudos
#permisão geral, apenas essa "enxada.*"
#mySQL 8.0.33 OBRIGATORIO!!!
#no Banco de dados criar o e nomealo de enxada
url: jdbc:mysql://localhost:3306/enxada
user: enxada
password: teste123

quantidadeDeHome: 3 #Quantas homes seram liberadas

tempoDeRecargaHome: 3 #Seg

particulaDestinoDoTeleport: CLOUD #Particula que ira aparecer ao Teleporta

quantidadeParticulaDestino: 10 # quantidade de pparticula ao explodir

#Wind Charge

windChargeVanilla: false #false para Desativa o WindCharge do Minecraft normal
#true para Ativar, mas ira receber as caracteristicas das linhas abaixo

velocidadeDoWindCharge: 1.0 #velocidade que ele ira percorrer

forcaWindCharge: 4.0 #minimo 1.0

particulaVoado: CRIT_MAGIC # rastro de particula que ele deixa

ParticulaPorTickVoado: 6 #intervalos de tick de aparição, a cada 6 equivale a 1seg

ParticulaPorAparicaoVoado: 10 #quantas irão ser geradas por aparição

particulaExplocao: EXPLOSION_LARGE #particula que ira aparecer na exploção

quantidadeDeParticulasAoExplodir: 10 #quantidade de particula ao explodir


#===Lista de Particulas===#obeservação existem mais
#ASH
#BARRIER
#BLOCK_CRACK
#BLOCK_DUST
#BUBBLE_COLUMN_UP
#BUBBLE_POP
#CAMPFIRE_COSY_SMOKE
#CAMPFIRE_SIGNAL_SMOKE
#CLOUD
#COMPOSTER
#CRIMSON_SPORE
#CRIT
#CRIT_MAGIC
#DAMAGE_INDICATOR
#DRAGON_BREATH
#DRIPPING_HONEY
#DRIPPING_LAVA
#DRIPPING_OBSIDIAN_TEAR
#DRIPPING_WATER
#DRIP_LAVA
#DRIP_OBSIDIAN_TEAR
#DRIP_WATER
#ENCHANTMENT_TABLE
#END_ROD
#ENDER
#EXPLOSION_HUGE
#EXPLOSION_LARGE
#EXPLOSION_NORMAL
#FALLING_HONEY
#FALLING_LAVA
#FALLING_NECTAR
#FALLING_OBSIDIAN_TEAR
#FALLING_WATER
#FIREWORKS_SPARK
#FLAME
#FLASH
#HAPPY_VILLAGER
#HEART
#INSTANT_EFFECT
#ITEM_CRACK
#LAVA
#LANDING_HONEY
#LANDING_LAVA
#LANDING_OBSIDIAN_TEAR
#MOB_APPEARANCE
#NAUTILUS
#NOTE
#POOF
#PORTAL
#RAIN
#SMOKE_LARGE
#SMOKE_NORMAL
#SNEEZE
#SNOW_SHOVEL
#SNOWBALL
#SOUL
#SOUL_FIRE_FLAME
#SPIT
#SQUID_INK
#SUSPENDED
#SUSPENDED_DEPTH
#SWEEP_ATTACK
#TOTEM
#TOWN_AURA
#WARPED_SPORE
#WATER_BUBBLE
#WATER_SPLASH
#WATER_WAKE
#WITCH